Update deprecated Dask `LocalCluster` method parameters in PyRosetta unit tests (#726)
This quick PR aims to update some PyRosetta tests' usage of the
deprecated `diagnostics_port` parameter in Dask's `LocalCluster`
constructor, resulting in the following error since release `2026.6.0`:
```
TypeError: Server.__init__() got an unexpected keyword argument 'diagnostics_port'
```